### PR TITLE
Fix chunk functions

### PR DESCRIPTION
**Pull request by kdorheim**
There were some issues with the chunk/get_chunk functions that meant that the code couldn't extract data from the smoothed ESM data 😔. This PR should fix that though! @abigailsnyder can you take a look at it when you get a chance? I am wondering if the functions we have not might want to be wrapped in another function so that we don't have to set up so many for loops, but that might be a problem for another day. 

@abigailsnyder and @claudiatebaldi here are some exciting results! The values and rates of change sampled from the different experiments and ensemble output from CanESM. While there is some overlap (meaning that we will have some tie-breakers) but I was pretty surprised by how spread out the ensemble members of the same experiments were. 

image

Here is the lab notebook walking through some of the questions we had while we were building these functions. Also, it shows to use the function to apply it to a grouped data frame (this took longer than expected to figure out bleh)
[Get_Chunk_Info_2021-02-18.pdf](https://github.com/JGCRI/stitches/files/6119219/Get_Chunk_Info_2021-02-18.pdf)

### CODE REVIEW

**Comment by abigailsnyder** [comment]
> to apply it to a grouped data frame (this took longer than expected to figure out bleh)

Same with figuring out the semi-smoothing on grouped data. The pain.

**Comment by claudiatebaldi** [comment]
Are the little sub-clusters for the same colors composed of the different ensemble members?

So, the idea would be to use some kind of nearest neighbor algorithm in this space, throwing on this graph the values of the hector produced (eventually) GSAT and finding the closest point(s) to each.

Is there a way to produce some stitched time series quickly to compare to the real ensemble members? Like by leaving out one of the SSP scenarios in turn, and building a stitched ensemble to compare to it? Of course we would want to do this for the intermediate scenarios, not for the highest/lowest.

From: Kalyn R. Dorheim ***@***.***>
Date: Wednesday, March 10, 2021 at 5:49 PM
To: JGCRI/stitches ***@***.***>
Cc: Tebaldi, Claudia ***@***.***>, Mention ***@***.***>
Subject: [JGCRI/stitches] Fix chunk functions (#9)
Check twice before you click! This email originated from outside PNNL.


There were some issues with the chunk/get_chunk functions that meant that the code couldn't extract data from the smoothed ESM data 😔. This PR should fix that though! @abigailsnyder<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fabigailsnyder&data=04%7C01%7Cclaudia.tebaldi%40pnnl.gov%7Cd06777fb69fe4187ff9b08d8e416c189%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C1%7C637510133689325107%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fnvq%2F1NUQk8u80YxO6G6fIuMibeCoft7ARva0HcztWU%3D&reserved=0> can you take a look at it when you get a chance? I am wondering if the functions we have not might want to be wrapped in another function so that we don't have to set up so many for loops, but that might be a problem for another day.

@abigailsnyder<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fabigailsnyder&data=04%7C01%7Cclaudia.tebaldi%40pnnl.gov%7Cd06777fb69fe4187ff9b08d8e416c189%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C1%7C637510133689335062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LunLrVyOwEuWZFv%2FyV4%2FUufj1YURfCgmunpb3lX3kfw%3D&reserved=0> and @claudiatebaldi<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fclaudiatebaldi&data=04%7C01%7Cclaudia.tebaldi%40pnnl.gov%7Cd06777fb69fe4187ff9b08d8e416c189%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C1%7C637510133689335062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NnduuScnaasd%2FBVv%2BdVY2fsQ8i5u3TzxCCAjp8MqnEc%3D&reserved=0> here are some exciting results! The values and rates of change sampled from the different experiments and ensemble output from CanESM. While there is some overlap (meaning that we will have some tie-breakers) but I was pretty surprised by how spread out the ensemble members of the same experiments were.

[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F27299759%2F110706861-7ddbda00-81c6-11eb-8524-1bbc9082f6b8.png&data=04%7C01%7Cclaudia.tebaldi%40pnnl.gov%7Cd06777fb69fe4187ff9b08d8e416c189%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C1%7C637510133689345016%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2pIyxv6tOqwfnB%2BKJgEolr3rRMlPHKLNXyZvtsNgo%2FI%3D&reserved=0>

Here is the lab notebook walking through some of the questions we had while we were building these functions. Also, it shows to use the function to apply it to a grouped data frame (this took longer than expected to figure out bleh)
Get_Chunk_Info_2021-02-18.pdf<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJGCRI%2Fstitches%2Ffiles%2F6119219%2FGet_Chunk_Info_2021-02-18.pdf&data=04%7C01%7Cclaudia.tebaldi%40pnnl.gov%7Cd06777fb69fe4187ff9b08d8e416c189%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C1%7C637510133689345016%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8q94mI3wHM5TpNJzRbfmSslVYXbp13NzrQu%2Fzv9TIS4%3D&reserved=0>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/JGCRI/stitches/pull/9<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJGCRI%2Fstitches%2Fpull%2F9&data=04%7C01%7Cclaudia.tebaldi%40pnnl.gov%7Cd06777fb69fe4187ff9b08d8e416c189%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C1%7C637510133689354973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6d9SXHq1yWiM0hI8DmiGHzd%2B2vxPL7nRUlHDPIzqZEg%3D&reserved=0>

Commit Summary

  *   fix functions used to extract the chunk information

File Changes

  *   M stitches/dev_matchup.py<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJGCRI%2Fstitches%2Fpull%2F9%2Ffiles%23diff-ea21396af3e7b542ddb2e8e2ffcbb83326c69107efefa9b65afc03d250413349&data=04%7C01%7Cclaudia.tebaldi%40pnnl.gov%7Cd06777fb69fe4187ff9b08d8e416c189%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C1%7C637510133689354973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BD1JnfZu7BBzHIPDTVROdnrfaVZRT3zkCuh0CQ6WYK0%3D&reserved=0> (21)

Patch Links:

  *   https://github.com/JGCRI/stitches/pull/9.patch<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJGCRI%2Fstitches%2Fpull%2F9.patch&data=04%7C01%7Cclaudia.tebaldi%40pnnl.gov%7Cd06777fb69fe4187ff9b08d8e416c189%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C1%7C637510133689364931%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=j5J%2BUX2yuD2z%2B313bC9Z526NB9pTomYXhYVPtYE0z28%3D&reserved=0>
  *   https://github.com/JGCRI/stitches/pull/9.diff<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJGCRI%2Fstitches%2Fpull%2F9.diff&data=04%7C01%7Cclaudia.tebaldi%40pnnl.gov%7Cd06777fb69fe4187ff9b08d8e416c189%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C1%7C637510133689364931%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=W6%2BSkprF78BB6D1h2MZZGR2af5xy6rjxAwXMhZr7tEc%3D&reserved=0>

**Comment by kdorheim** [comment]
> Are the little sub-clusters for the same colors composed of the different ensemble members? 

Yes that is exactly what they are! 


> So, the idea would be to use some kind of nearest neighbor algorithm in this space, throwing on this graph the values of the hector produced (eventually) GSAT and finding the closest point(s) to each. 

👍 

> Is there a way to produce some stitched time series quickly to compare to the real ensemble members? Like by leaving out one of the SSP scenarios in turn, and building a stitched ensemble to compare to it? Of course we would want to do this for the intermediate scenarios, not for the highest/lowest.

Yes the plan that @abigailsnyder and I discussed for the first pass would be to start out using ssp858 and trying to emulate one of the ssp245 and then compare the stiched product with the original data. Does that sound okay or should we only withhold the single ssp scenario that we are trying to emulate?

**Comment by claudiatebaldi** [comment]
That’s a good point. I think it is indeed better not to do what I suggested because in realistic applications we would not have all that bounty of scenarios…so I think the realistic situation would be that a model would have run a low and a high scenario to bracket the space, and therefore we would have something like ssp5-8.5 and ssp1-2.6  (or ssp1-1.9) and we would try to approximate everything in between…as for the choice between SSP1-1.9 amd SSP1-2.6 as the lower bracket, ‘d be curious if we could approximate SSP1-1.9 by historical and ssp1-2.6. It’s an interesting case because of the flatness (when not overshoot) of the trajectory. Alternatively one would consider ssp1-1.9 as the lower bracket. I don’t have a lot to give as wisdom here but I could see that in a concerted effort to run only two scenarios in service of stitching a modeling center would go as low as plausible and as high as plausible. What do you think?


From: Kalyn R. Dorheim ***@***.***>
Date: Thursday, March 11, 2021 at 10:05 AM
To: JGCRI/stitches ***@***.***>
Cc: Tebaldi, Claudia ***@***.***>, Mention ***@***.***>
Subject: Re: [JGCRI/stitches] Fix chunk functions (#9)
Check twice before you click! This email originated from outside PNNL.


Are the little sub-clusters for the same colors composed of the different ensemble members?

Yes that is exactly what they are!

So, the idea would be to use some kind of nearest neighbor algorithm in this space, throwing on this graph the values of the hector produced (eventually) GSAT and finding the closest point(s) to each.

👍

Is there a way to produce some stitched time series quickly to compare to the real ensemble members? Like by leaving out one of the SSP scenarios in turn, and building a stitched ensemble to compare to it? Of course we would want to do this for the intermediate scenarios, not for the highest/lowest.

Yes the plan that @abigailsnyder<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fabigailsnyder&data=04%7C01%7Cclaudia.tebaldi%40pnnl.gov%7C470aff5bda7d452c779108d8e49f06fb%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C637510719304382181%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oypyXpS15q2Lhjkyec%2F6j5djpC82%2Fmgf0jxB6YDMAXw%3D&reserved=0> and I discussed for the first pass would be to start out using ssp858 and trying to emulate one of the ssp245 and then compare the stiched product with the original data. Does that sound okay or should we only withhold the single ssp scenario that we are trying to emulate?

**Review by abigailsnyder — COMMENTED** [review]
@kdorheim I'm not too worried about the for-loops in functions currently. I went through our functions and there are only for loops in the `calculate_rolling_mean` function (to copy the historical data into each future scenario) and in the `get_chunk_info` function. 

For the one in the rolling mean calculation, I think that we could re-work it with a group_by and apply. Or maybe even just as a left_join with some reshaping between wide and long data. But I also don't think this function gets called often enough  + I don't think this for loop is slow enough for it to be pressing to update. I can open an issue with these ideas and we can deal with it at some point.

For the for loop in `get_chunk_info`, if I was doing it in R, I would probably do it as a `split-lapply-do.call(rbind)` sequence. 
In terms of having to call `get_chunk_info` (which has a for loop) within a for loop like in your pdf, there is like a noticeable pause while you wait for it to run. It's not terrible though. I still don't quite have where this fits into the general flow of creating the archive and using the archive to generate new ensemble members. Are you envisioning this function being run sort of one time in our creating of the archive, or like one time when creating a new set of ensemble members, or one time for each new ensemble member that gets created? If it's that last one, we should probably look up options for the python translation of an R `split-lapply-do.call(rbind)`to speed it up. If it's something that really only gets called once at some point while using the package, I'm not too worried about the speed.

so @kdorheim let me know how you think this function will be used, and we can decide if we need to speed it up now or not. 


As a side note, for the pdf write up, I could not get plotnine to work in pycharm, with warning "UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail."  I'm not concerned since the workbook isn't part of this PR and I recreated the plots using seaborn but we should probably figure this out at some point. I also only tried replicating the ESM data part since I don't have testing hector data handy.

**Comment by kdorheim** [comment]
Here is the hector data I've been using. 
[hector_data.csv.zip](https://github.com/JGCRI/stitches/files/6133119/hector_data.csv.zip)

**Comment by abigailsnyder** [comment]
@kdorheim edit to add that I think this could be merged as is, it's up to you whether you want us to try to improve the speed of the call to the chunking functions now in this PR or just open as an issue to address later

**Pull request merged**
